import { NewItemValues } from '../../components/add-firebase/add-item.component';

export enum CATEGORIES_ACTION_TYPES {
  FETCH_CATEGORIES_INITIAL_STATE = 'category/FETCH_CATEGORIES_INITIAL_STATE',
  FETCH_UPDATE_CATEGORIES = 'category/FETCH_UPDATE_CATEGORIES',
  FETCH_CATEGORIES_START = 'category/FETCH_CATEGORIES_START',
  FETCH_PREVIEW_CATEGORIES_START = 'category/FETCH_PREVIEW_CATEGORIES_START',
  FETCH_SUB_CATEGORY = 'category/FETCH_SUB_CATEGORY',
  FETCH_SUB_CATEGORY_SUCCEEDED = 'category/FETCH_SUB_CATEGORY_SUCCEEDED',
  FETCH_SUB_CATEGORY_DATA = 'category/FETCH_SUB_CATEGORY_DATA',
  FETCH_SUB_CATEGORY_DATA_SUCCEEDED = 'category/FETCH_SUB_CATEGORY_DATA_SUCCEEDED',
  FETCH_ALL_CATEGORIES_START = 'category/FETCH_ALL_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS = 'category/FETCH_CATEGORIES_SUCCESS',
  FETCH_ALL_CATEGORIES_SUCCESS = 'category/FETCH_ALL_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILED = 'category/FETCH_CATEGORIES_FAILED',
}

export type Category = {
  title: string;
  imageUrl?: string;
  items: NewItemValues[];
};

export type CategoryMap = {
  [key: string]: NewItemValues[];
};
